[package]
name = "rum_compiler"
version = "0.0.0"
edition = "2021"

[lib]
path = "./lib.rs"

[dependencies]
rum_lang    = { path="../rum_lang" }
core_lang       = { path="../core" }
num-traits        = "0.2.17"

[dependencies.radlr_rust_runtime]
path = "../../../lib_radlr/crates/radlr-rust-runtime"

[build-dependencies.radlr_build]
path = "../../../lib_radlr/crates/radlr-build"

