[workspace]

members = [
  "./crates/compiler",
  "./crates/core",
  "./crates/common",
  "./crates/rum_lang"
]

resolver = "2"

[profile.dev]
debug = 2

[profile.release]
opt-level=3
debug = 0

[profile.release-with-debug]
inherits = "release"
debug = true
