[package]
name = "core_lang"
version = "0.0.0"
edition = "2021"

build = "./build.rs"

[lib]
path = "./lib.rs"

[dependencies.radlr_rust_runtime]
workspace = true

[build-dependencies.radlr_build]
workspace = true

